// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // #### secret keys #### 
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjdQXm9Jw7Rq1n_JPotNsQDu6LSSV03WI',
    appId: '1:242170350559:android:a5e4b3da1b390a282bd26a',
    messagingSenderId: '242170350559',
    projectId: 'awr-live-location-tracking',
    storageBucket: 'awr-live-location-tracking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf4Xh8UQSSgzwRgc9Dql0hK4w8TXgs21Y',
    appId: '1:242170350559:ios:ef3c4fbc54fabf112bd26a',
    messagingSenderId: '242170350559',
    projectId: 'awr-live-location-tracking',
    storageBucket: 'awr-live-location-tracking.appspot.com',
    iosBundleId: 'com.example.awrFlutterApplication',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0GYFUZsbbCMpW_eQkEn3rk7tsEow_02I',
    appId: '1:242170350559:web:2e0d5d1a55e305e82bd26a',
    messagingSenderId: '242170350559',
    projectId: 'awr-live-location-tracking',
    authDomain: 'awr-live-location-tracking.firebaseapp.com',
    storageBucket: 'awr-live-location-tracking.appspot.com',
    measurementId: 'G-5VZWJFQMD4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf4Xh8UQSSgzwRgc9Dql0hK4w8TXgs21Y',
    appId: '1:242170350559:ios:ef3c4fbc54fabf112bd26a',
    messagingSenderId: '242170350559',
    projectId: 'awr-live-location-tracking',
    storageBucket: 'awr-live-location-tracking.appspot.com',
    iosBundleId: 'com.example.awrFlutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0GYFUZsbbCMpW_eQkEn3rk7tsEow_02I',
    appId: '1:242170350559:web:f164f16a173ecdc22bd26a',
    messagingSenderId: '242170350559',
    projectId: 'awr-live-location-tracking',
    authDomain: 'awr-live-location-tracking.firebaseapp.com',
    storageBucket: 'awr-live-location-tracking.appspot.com',
    measurementId: 'G-QL49S821EC',
  );

}